version: '3.7'

services:
  bot:
    container_name: tg_bot
    build: ./bot
    volumes:
      - ./bot/logs/:/bot/bot/logs
#    volumes:
#      - /Users/danyapetrovich/PycharmProjects/telegram_bot/bot:/data